# Generated by Django 5.0.6 on 2024-06-11 04:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idProducto', models.BigAutoField(db_column='idCategoria', primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_column='Nombre', max_length=45)),
            ],
            options={
                'verbose_name_plural': 'Categoria',
            },
        ),
        migrations.CreateModel(
            name='Comprador',
            fields=[
                ('idcomprador', models.AutoField(db_column='idPersona', primary_key=True, serialize=False)),
                ('nombres', models.CharField(db_column='Nombres', max_length=50)),
                ('apellidos', models.CharField(db_column='Apellidos', max_length=50)),
                ('numidentificacion', models.BigIntegerField(db_column='NumIdentificacion')),
                ('numcelular', models.BigIntegerField(db_column='NumCelular')),
                ('correoelectronico', models.CharField(db_column='CorreoElectronico', max_length=45)),
                ('direccion', models.CharField(db_column='direccion', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Perfilusuario',
            fields=[
                ('idroles', models.AutoField(db_column='idRoles', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=45)),
                ('descripcionrol', models.TextField(blank=True, db_column='descripcionRol', null=True)),
                ('user', models.ForeignKey(db_column='Usuario', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Perfil Usuario',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.BigAutoField(db_column='idProduco', primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_column='nombre', max_length=100)),
                ('disponible', models.BooleanField(db_column='Disponible', default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_column='Fecha de subida')),
                ('precio', models.DecimalField(db_column='Precio', decimal_places=3, default=None, max_digits=6, verbose_name='Precio')),
                ('descripcion', models.TextField(blank=True, db_column='Descripcion', default=None, max_length=150, null=True)),
                ('foto', models.ImageField(db_column='Foto', null=True, upload_to='products')),
                ('estado', models.BooleanField(blank=True, db_column='estado', default=True)),
                ('categoria', models.ForeignKey(db_column='Categoria', default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='home.categoria')),
                ('user', models.ForeignKey(db_column='Usuario', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Mis_productos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Productos',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='carrito_compras',
            fields=[
                ('idcar', models.AutoField(db_column='idCar', primary_key=True, serialize=False)),
                ('productos', models.ForeignKey(db_column='productos', default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='home.producto')),
            ],
        ),
    ]
